### ISSUE TITLE
Which version of Pytorch_lightning?

### ISSUE THREAD

**Issue by yuanxuanS** [IIT-PAVIS/Look_Around_And_Learn#1]
Difference between pytorch_lightning varies a lot. Many issues need  to  be solved. Could you please tell me your version?

**Comment by morpheus1820** [comment]
Hi, we use `pytorch-lightning==1.5.8`

**Comment by yuanxuanS** [comment]
Thanks! How about gcc version?

**Comment by yuanxuanS** [comment]
I need it to install detectron2. Otherwise something wrong:
`ImportError: cannot import name '_C' from 'detectron2' (/home/users/wpp/Look_Around_And_Learn/third_parties/detectron2/detectron2/__init__.py)`

**Comment by yuanxuanS** [comment]
I need it to install detectron2. Otherwise something wrong:
`ImportError: /home/users/wpp/Look_Around_And_Learn/third_parties/detectron2/detectron2/_C.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1017SymbolicShapeMeta18init_is_contiguousEv`

**Comment by morpheus1820** [comment]
It looks like you are using python 3.8. See here, we use python 3.7 in our environment: https://github.com/IIT-PAVIS/Look_Around_And_Learn/blob/release/env.yml
