### ISSUE TITLE
It seems that no download link of objectnav tasks are attached.

### ISSUE THREAD

**Issue by yuanxuanS** [IIT-PAVIS/Look_Around_And_Learn#2]
Could you please tell me it?

**Comment by morpheus1820** [comment]
Thanks, we will update the instructions. Objectnav episodes can be found here
`wget --no-check-certificate 'https://drive.google.com/uc?export=download&id=1tslnZAkH8m3V5nP8pbtBmaR2XEfr8Rau' -O objectnav_gibson_v1.1.zip`

https://github.com/devendrachaplot/Object-Goal-Navigation
