### ISSUE TITLE
Which part do you use in Gibson scene datasets?

### ISSUE THREAD

**Issue by yuanxuanS** [IIT-PAVIS/Look_Around_And_Learn#3]
Thanks for your patience.
 I download Gibson dataset from its repo: https://github.com/StanfordVL/GibsonEnv/blob/master/gibson/data/README.md#download
But it has 20G data which is just 1.5G in your README.md. Could you please show me your download link of Gibson and MatterPort3D scene datasets? They are not in README.md.

**Comment by morpheus1820** [comment]
For Gibson, you can download Gibson tiny, see https://github.com/IIT-PAVIS/Look_Around_And_Learn?tab=readme-ov-file#gibson
Then you need to generate the semantic annotations following here https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#gibson-and-3dscenegraph-datasets

For mp3d, also see habitat-sim https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset

**Comment by yuanxuanS** [comment]
I found that I need to joint SDSS to get acess the 3DSceneGraph dataset. Can I join this group that I'm not a member of them? And I don't know any other way to get access it.
