### ISSUE TITLE
How to ensure sample frame which has detected object in finetune stage?

### ISSUE THREAD

**Issue by yuanxuanS** [IIT-PAVIS/Look_Around_And_Learn#4]
When sampled data in exploration have no detected objected, the `data['bbsgt'].get_bbs_as_gt()` is empty. And there would be error:
`  File "/home/users/wpp/Look_Around_And_Learn/experimenting_env/detector/dataset.py", line 219, in __getitem__
    transformed_rgbd, y = self._transform_batch(rgbd, y)
  File "/home/users/wpp/Look_Around_And_Learn/experimenting_env/detector/dataset.py", line 80, in _transform_batch
    transformed = self.transform(
  File "/home/users/wpp/miniconda3/envs/explore/lib/python3.8/site-packages/albumentations/core/composition.py", line 195, in __call__
    self._check_args(**data)
  File "/home/users/wpp/miniconda3/envs/explore/lib/python3.8/site-packages/albumentations/core/composition.py", line 279, in _check_args
    if not isinstance(data[0], np.ndarray):
IndexError: list index out of range`

**Comment by yuanxuanS** [comment]
Could you please show me how to run `finetune_improving_labels.py` with proper config file?

**Comment by yuanxuanS** [comment]
How can I get the 'fix_test' test dataset here?
![image](https://github.com/user-attachments/assets/affda3ec-c399-4248-81bd-679776cb236a)

**Comment by morpheus1820** [comment]
You can use the `sample_test_set.py` script

**Comment by morpheus1820** [comment]
> How can I get the 'fix_test' test dataset here? ![image](https://private-user-images.githubusercontent.com/70061770/370734193-affda3ec-c399-4248-81bd-679776cb236a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc0MjY4MzEsIm5iZiI6MTcyNzQyNjUzMSwicGF0aCI6Ii83MDA2MTc3MC8zNzA3MzQxOTMtYWZmZGEzZWMtYzM5OS00MjQ4LTgxYmQtNjc5Nzc2Y2IyMzZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTI3VDA4NDIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwMTI0MWY1YWY5YjNlYmFmMGY1YWRlOWM0MTQ4Nzc3MjBhYmZhYzdlNzQ4YTE1ZTY3NzVjNjEwYzA4YTIzNjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yqPeZwsoMZxa4WVguVBsCXYJAIunNU9Lze6A_TUW-gI)

You can use the `sample_test_set.py` script

**Comment by yuanxuanS** [comment]
Thanks！
