### ISSUE TITLE
reproduce of original MaskRCNN model

### ISSUE THREAD

**Issue by yuanxuanS** [IIT-PAVIS/Look_Around_And_Learn#5]
When I infer with off-the-shelf MaskRCNN model, it shows bad prediction like this:
![微信图片_20241029161922](https://github.com/user-attachments/assets/6717c0c5-7c42-4819-b31d-f29e602ccf8b)
I set the test score threshold to 0.9.
Did you get this result as well?

**Comment by yuanxuanS** [comment]
I used detection_args of maskrcnn. And its config is:
`# @package _group_
config_file: ${base_dir}/third_parties/detectron2/configs/quick_schedules/mask_rcnn_R_50_FPN_inference_acc_test.yaml
confidence_threshold: 0.9
MODEL:
  ROI_HEADS:
    NMS_THRESH_TEST: 0.9

  
`

**Comment by morpheus1820** [comment]
Hi, this is the detectron2 configuration file we used,specified inside train_policy.yaml:
https://github.com/IIT-PAVIS/Look_Around_And_Learn/blob/e939597aac5de4c8a7f173bbf728cd2dc98d5ec8/confs/detectron_args/maskrcnn.yaml
